config/routes.rb
Rails.application.routes.draw do
  resources :teachers, only: :show do 
    resources :students, only: [:index, :new]
  end
  resources :students, only: [:index, :new]

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :teacher
    belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :courses
    has_many :teachers, through: :courses
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :courses
    has_many :students, through: :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @teacher = Teacher.find_by(id: params[:teacher_id])
    if @teacher
      #only load this teacher's students
      @students = @teacher.students
    else 
      #load all the students
      @students = Student.all
    end
  end

  def new 
    @student = Student.new
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def show
    @teacher = Teacher.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolRoster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%=f.label :grade %>
<%= f.text_field :grade %>

app/views/students/index.html.erb
<ul><% @students.each do |student| %>
    <li><%= student.name %></li>
<% end %></ul>

app/views/students/new.html.erb
make a new students:



<%= form_for(@student) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= render partial: 'form', locals: {f: f} %>

    <%= f.submit %>
<% end %>

def form_partial(local)
    <%= form_for(local) 
end

app/views/teachers/show.html.erb
<%= @teacher.name %>
<br>
<%= link_to "#{@teacher.name}'s students", teacher_students_path(@teacher) %>
<%= link_to "Make a new student", new_teacher_student_path(@teacher) %>